FROM node:20-alpine AS build
WORKDIR /ui
COPY control-panel/package*.json ./
RUN npm ci
COPY control-panel ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /ui/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
